apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-service-deployment
  labels:
    app: registry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-service
  template:
    metadata:
      labels:
        app: registry-service
    spec:
      containers:
      - name: registry-service
        image: tanukansaldocker123/codist-registry-testing-a2:amd64
        ports:
        - containerPort: 3333
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-service:7074/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7072
    targetPort: 3333
    nodePort: 30001