apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-deployment
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: tanukansaldocker123/codist-frontend:amd64
        imagePullPolicy: "Always"
        ports:
        - containerPort: 1776
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8813
    targetPort: 1776
    nodePort: 30243