apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7849 
      targetPort: 5432
      nodePort: 30064
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: tanukansal123/codist-postgres:amd64
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        # env: 
        # - name: API_HOST
        #   value: "0.0.0.0"
        # - name: POSTGRES_HOST
        #   value: "0.0.0.0"
        # - name: POSTGRES_PORT
        #   value: "5432"
        # - name: POSTGRES_USER
        #   value: postgres
        # - name: POSTGRES_PASSWORD
        #   value: admin
        # - name: POSTGRES_DBNAME
        #   value: demo_db