apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8074
      targetPort: 8085
      nodePort: 30032
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: metalman66/cicd-test:amd64
        ports:
        - containerPort: 8085
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PORT
          value: "7849"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DBNAME
          value: demo_db
