apiVersion: apps/v1
kind: Deployment
metadata:
  name: merra-plotting-service-deployment
  labels:
    app: merra-plotting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merra-plotting-service
  template:
    metadata:
      labels:
        app: merra-plotting-service
    spec:
      containers:
      - name: merra-plotting-service
        image: tanukansaldocker123/codist-merra-plotting:amd64
        ports:
        - containerPort: 6050
---
apiVersion: v1
kind: Service
metadata:
  name: merra-plotting-service
spec:
  selector:
    app: merra-plotting-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2000
    targetPort: 6050
    nodePort: 30047