name: Python Package Using Anaconda

on:
  push:
    branches: [ dockerChangesMerraPlotting ]
  pull_request:
    branches: [ dockerChangesMerraPlotting ]

env:
  RABBITMQ_HOST: localhost
  
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.2-management-alpine'
        host port: 5672
        rabbitmq user: 'user'
        rabbitmq password: 'password'

    - name: Creating ENV file
      run: cat example.env >> .env

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base

    - name: Initialising bash environment
      run: conda init bash

    - name: Activating conda server
      run: echo "conda activate base" > ~/.bashrc

    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Installing dependencies
      run: pip install -r requirements.txt 

    - name: Installing cartopy
      run: |
        conda install -c conda-forge cartopy
    
    - name: Check ENV
      run: |
        conda env list
    # - name: Docker Login
    #   run: |
    #     docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    # - name: Build the Docker Image
    #   run: |
    #     docker build -t ${{secrets.DOCKER_USERNAME}}/codist-merra-ingestion:arm64 .
    #     docker build -t ${{secrets.DOCKER_USERNAME}}/codist-merra-ingestion:amd64 .
    
    # - name: Docker Push
    #   run: |
    #     docker push ${{secrets.DOCKER_USERNAME}}/codist-merra-ingestion:arm64
    #     docker push ${{secrets.DOCKER_USERNAME}}/codist-merra-ingestion:amd64

    - name: Running appliations
      run: python consumer.py
     
      