name: Python Package Using Anaconda

on:
  push:
    branches: [ dockerChangesMerraPlotting ]
  pull_request:
    branches: [ dockerChangesMerraPlotting ]
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # services:
    #   rabbitmq:
    #     image: rabbitmq:management
    #     env:
    #       RABBITMQ_DEFAULT_USER: user
    #       RABBITMQ_DEFAULT_PASS: password
    #     ports:
    #       - 5672

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myplotenv
          environment-file: environmentCi.yml
          python-version: 3.8
          auto-activate-base: false

      - uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 5672
          rabbitmq user: 'user'
          rabbitmq password: 'password'

      - name: Creating ENV file
        run: cat example.env >> .env

      - run: |
          python consumer.py
    