name: Node.js CI

on:
  push:
    branches: [ dev-registry ]
  pull_request:
    branches: [ dev-registry ]

env:
  MONGO_URL : mongodb://localhost:27017/registry

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start Docker for Mongodb
      run: docker run -d -p 27017:27017 mongo
    - name: Creating ENV file
      run: cat example.env >> .env
    - run: npm install
    
    # - name: Docker Login
    #   run: |
    #     docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    # - name: Build the Docker Image
    #   run: |
    #     docker build -t ${{secrets.DOCKER_USERNAME}}/codist-registry:arm64 .
    #     docker build -t ${{secrets.DOCKER_USERNAME}}/codist-registry:amd64 .
    
    # - name: Docker Push
    #   run: |
    #     docker push ${{secrets.DOCKER_USERNAME}}/codist-registry:arm64
    #     docker push ${{secrets.DOCKER_USERNAME}}/codist-registry:amd64

    - run: npm run start